language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "4.0"
  - "5.0"
  - "6.0"
  - "stable"
before_script:
  - cp config.js ../config.js
  - npm install
script:
  - gulp initProject
  - gulp sass
  - gulp include
  - gulp clean
  - gulp merge
