language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6.0"
  - "7.0"
  - "8.0"
  - "stable"
before_script:
  - cp qmui.config.js ../qmui.config.js
  - npm install
script:
  - gulp initProject
  - gulp list
  - gulp sass
  - gulp include
  - gulp clean
  - gulp merge
